services:
  - type: web
    name: quizmaster
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --include=dev && node scripts/sync-db-provider.js && npx prisma generate && (npx prisma migrate deploy || npx prisma db push --accept-data-loss) && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quizmaster-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: quizmaster-db
    plan: free
    region: singapore
