-- AlterTable
ALTER TABLE "Question" ADD COLUMN "totalAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN "correctCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN "countA" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN "countB" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN "countC" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN "countD" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "WrongQuestionRecord" ADD COLUMN "totalAttempts" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "WrongQuestionRecord" ADD COLUMN "correctCount" INTEGER NOT NULL DEFAULT 0;
