const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

function normalizeText(text) {
  if (!text) return "";
  let result = text
    .replace(/[\uFF01-\uFF5E]/g, (ch) =>
      String.fromCharCode(ch.charCodeAt(0) - 0xfee0)
    )
    .replace(/\u3000/g, " ")
    .toLowerCase();
  return result.replace(/[\s\p{P}\p{S}]/gu, "");
}

const questionsPool = [
  // 專案管理 - 敏捷與 Scrum
  {
    stem: "在 Scrum 敏捷框架中，下列何者不屬於 Scrum 的三個核心角色之一？",
    type: "SINGLE",
    optionA: "產品負責人 (Product Owner)",
    optionB: "Scrum 導師 (Scrum Master)",
    optionC: "專案經理 (Project Manager)",
    optionD: "開發團隊 (Development Team)",
    correctAnswers: "C",
    explanation: "Scrum 框架定義的三個角色為 Product Owner、Scrum Master 與 Development Team。傳統專案經理的角色職責已被這三個角色分散承擔。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "敏捷, Scrum",
  },
  {
    stem: "在敏捷專案管理中，關於每日站立會議 (Daily Standup) 的敘述，下列哪些是正確的？",
    type: "MULTIPLE",
    optionA: "會議時間通常嚴格限制在 15 分鐘以內",
    optionB: "會議目的主要是向專案經理報告詳細績效指標",
    optionC: "團隊成員分享昨天完成的事項、今天預計完成的事項與遇到的阻礙",
    optionD: "若有複雜議題需要深究，應在站會結束後由相關人員另行討論",
    correctAnswers: "A,C,D",
    explanation: "站立會議是為團隊內部同步與暴露阻礙而設，並非傳統由上而下的業績匯報；深入技術細節應於會後另行召集討論。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "Scrum, 站立會議",
  },
  {
    stem: "下列哪一種圖表通常用於追蹤 Scrum 衝刺 (Sprint) 期間團隊剩餘工作量隨時間遞減的趨勢？",
    type: "SINGLE",
    optionA: "甘特圖 (Gantt Chart)",
    optionB: "燃盡圖 (Burndown Chart)",
    optionC: "柏拉圖 (Pareto Chart)",
    optionD: "魚骨圖 (Ishikawa Diagram)",
    correctAnswers: "B",
    explanation: "燃盡圖（Burndown Chart）橫軸為衝刺天數，縱軸為剩餘故事點或工時，用於即時掌握進度是否能如期完成。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "敏捷, 燃盡圖",
  },
  {
    stem: "在專案管理中，工作分解結構 (WBS, Work Breakdown Structure) 的主要特性與功用包含下列哪些？",
    type: "MULTIPLE",
    optionA: "它是以可交付成果 (Deliverables) 為導向的階層式分解",
    optionB: "WBS 的最底層稱為工作包 (Work Package)",
    optionC: "WBS 必須遵循 100% 原則，即下層工作總和需完全涵蓋上層範圍",
    optionD: "WBS 主要用來表示活動前後順序與相依時程關係",
    correctAnswers: "A,B,C",
    explanation: "WBS 是範疇分解工具，不呈現時程或前後相依性；時程與前後關係由網路圖 (Network Diagram) 或甘特圖表示。",
    category: "專案管理",
    difficulty: "HARD",
    tags: "範疇管理, WBS",
  },
  {
    stem: "若某專案活動的最樂觀時間為 4 天，最可能時間為 9 天，最悲觀時間為 20 天，依 PERT 三點估算法，該活動的期望工期 (Expected Time) 為多少天？",
    type: "SINGLE",
    optionA: "10 天",
    optionB: "11 天",
    optionC: "9 天",
    optionD: "12 天",
    correctAnswers: "A",
    explanation: "PERT 期望時間公式為 TE = (O + 4M + P) / 6 = (4 + 4*9 + 20) / 6 = (4 + 36 + 20) / 6 = 60 / 6 = 10 天。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "時程管理, PERT",
  },
  {
    stem: "在專案要徑法 (Critical Path Method, CPM) 中，關於「要徑 (Critical Path)」的特性，下列敘述哪些是正確的？",
    type: "MULTIPLE",
    optionA: "要徑是專案網路圖中總工期最長的路徑",
    optionB: "要徑上的活動其總寬裕時間 (Total Float) 通常為 0",
    optionC: "要徑上的任何活動發生延誤，都會直接導致整個專案的完工時間延後",
    optionD: "一個專案絕對只能有一條要徑，不可能存在多條要徑",
    correctAnswers: "A,B,C",
    explanation: "一個專案可能同時存在兩條或以上工期相同的要徑，因此 D 選項錯誤。",
    category: "專案管理",
    difficulty: "HARD",
    tags: "時程管理, 要徑法",
  },
  {
    stem: "專案進行中，若實獲值分析 (EVM) 顯示成本績效指標 CPI = 0.85，時程績效指標 SPI = 1.15，代表目前專案的執行狀況為何？",
    type: "SINGLE",
    optionA: "成本超支，進度超前",
    optionB: "成本節省，進度落後",
    optionC: "成本超支，進度落後",
    optionD: "成本節省，進度超前",
    correctAnswers: "A",
    explanation: "CPI < 1 代表成本超支 (每花 1 元僅獲得 0.85 元價值)；SPI > 1 代表進度超前 (實際進度快於預定進度)。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "成本管理, EVM",
  },
  {
    stem: "面對專案中的負面風險 (威脅)，下列哪些屬於 PMBOK 定義的標準風險因應策略？",
    type: "MULTIPLE",
    optionA: "規避 (Avoid)",
    optionB: "轉移 (Transfer)",
    optionC: "減輕 (Mitigate)",
    optionD: "開拓 (Exploit)",
    correctAnswers: "A,B,C",
    explanation: "開拓 (Exploit) 是針對正面風險 (機會) 的因應策略，而非負面威脅的策略。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "風險管理",
  },
  {
    stem: "專案管理三重限制 (Triple Constraints) 的傳統金三角包含哪三個核心維度？",
    type: "SINGLE",
    optionA: "範疇 (Scope)、時間 (Time)、成本 (Cost)",
    optionB: "人員 (People)、流程 (Process)、工具 (Tools)",
    optionC: "品質 (Quality)、風險 (Risk)、利害關係人 (Stakeholder)",
    optionD: "收益 (Benefit)、戰略 (Strategy)、治理 (Governance)",
    correctAnswers: "A",
    explanation: "傳統專案管理三重限制核心為範疇、時程（時間）與成本，三者互相制衡並共同影響品質。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "專案基礎",
  },
  {
    stem: "關於專案利害關係人管理 (Stakeholder Management)，下列哪些策略通常適用於「高權力、高利益」的利害關係人？",
    type: "MULTIPLE",
    optionA: "緊密管理 (Manage Closely)",
    optionB: "定期進行雙向溝通與諮詢",
    optionC: "僅進行最低限度的單向通知 (Monitor)",
    optionD: "主動爭取其對專案目標的支持與背書",
    correctAnswers: "A,B,D",
    explanation: "在權力利益矩陣中，高權力且高利益者為核心關鍵人物，必須密切管理與深度參與，低權力低利益者才採取監督 (Monitor)。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "利害關係人",
  },
  {
    stem: "在專案變更管理流程中，任何基準變更請求在正式執行前，通常必須經過何者審核與批准？",
    type: "SINGLE",
    optionA: "變更管制委員會 (Change Control Board, CCB)",
    optionB: "單一開發工程師",
    optionC: "終端使用者 (End User)",
    optionD: "競爭對手",
    correctAnswers: "A",
    explanation: "正式專案由變更管制委員會 (CCB) 負責評估變更對範疇、時程、成本的綜合衝擊後決定核准或否決。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "整合管理, CCB",
  },
  {
    stem: "關於敏捷估算中的「規劃撲克 (Planning Poker)」，下列哪些敘述是正確的？",
    type: "MULTIPLE",
    optionA: "撲克牌數字通常採用費氏數列 (Fibonacci Sequence) 或其變形",
    optionB: "主要用來評估使用者故事的相對複雜度 (Story Points)",
    optionC: "每位團隊成員同時出牌，藉由亮牌避免錨定效應 (Anchoring Effect)",
    optionD: "最高分與最低分者通常需要解釋各自的考量點",
    correctAnswers: "A,B,C,D",
    explanation: "四個選項皆為規劃撲克的標準原則與運作流程。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "敏捷, 規劃撲克",
  },
  {
    stem: "在專案品質管理中，「品質保證 (Quality Assurance, QA)」與「品質管制 (Quality Control, QC)」的主要區別為何？",
    type: "SINGLE",
    optionA: "QA 著重於流程導向以預防缺陷，QC 著重於產品導向以偵測缺陷",
    optionB: "QA 只在專案結束時執行，QC 在專案初期執行",
    optionC: "QA 由客戶執行，QC 由供應商執行",
    optionD: "兩者完全相同無任何區別",
    correctAnswers: "A",
    explanation: "QA（品質保證）關注流程與防患於未然；QC（品質管制）關注產出物的檢驗與抽查。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "品質管理",
  },
  {
    stem: "下列哪些技術可以用來壓縮專案時程 (Schedule Compression)？",
    type: "MULTIPLE",
    optionA: "趕工 (Crashing)",
    optionB: "快速跟進 (Fast Tracking)",
    optionC: "範疇蔓延 (Scope Creep)",
    optionD: "增加資源投入以縮短工期",
    correctAnswers: "A,B,D",
    explanation: "趕工（增加資源）與快速跟進（將原本順序執行的活動改為並行）是兩種標準的時程壓縮技術；範疇蔓延是未經管制的範圍膨脹，會延長時程。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "時程管理",
  },
  {
    stem: "在專案合約類型中，哪種合約形式對買方 (Buyer) 的成本風險最高，而對賣方 (Seller) 風險最低？",
    type: "SINGLE",
    optionA: "總價合約 (Firm Fixed Price, FFP)",
    optionB: "成本補償合約 (Cost-Reimbursable / Cost Plus)",
    optionC: "工料合約 (Time and Material, T&M)",
    optionD: "獎勵費用合約",
    correctAnswers: "B",
    explanation: "在成本補償合約中，買方需實報實銷所有實際支出，因此若成本失控買方承擔最大風險。",
    category: "專案管理",
    difficulty: "HARD",
    tags: "採購管理",
  },
  {
    stem: "看板方法 (Kanban) 的核心實踐原則包含下列哪些？",
    type: "MULTIPLE",
    optionA: "將工作流程視覺化 (Visualize the Workflow)",
    optionB: "限制在製品數量 (Limit WIP, Work in Progress)",
    optionC: "管理與改善流動 (Manage Flow)",
    optionD: "強制規定每次衝刺必須剛好兩週",
    correctAnswers: "A,B,C",
    explanation: "限制固定兩週衝刺是 Scrum 的特點，Kanban 是連續流動系統，沒有固定的時間盒 (Timebox) 限制。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "敏捷, Kanban",
  },
  {
    stem: "在專案溝通管理中，若一個專案團隊原本有 5 位成員，後來新增了 3 位成員，則溝通管道數量增加了幾條？",
    type: "SINGLE",
    optionA: "18 條",
    optionB: "28 條",
    optionC: "10 條",
    optionD: "8 條",
    correctAnswers: "A",
    explanation: "溝通管道公式為 N*(N-1)/2。原本 5 人：5*4/2 = 10 條；增加 3 人後為 8 人：8*7/2 = 28 條。增加數為 28 - 10 = 18 條。",
    category: "專案管理",
    difficulty: "HARD",
    tags: "溝通管理",
  },
  {
    stem: "關於專案章程 (Project Charter) 的功用，下列哪些是正確的？",
    type: "MULTIPLE",
    optionA: "由專案發起人 (Sponsor) 或高層主管簽署核准",
    optionB: "正式授權專案經理動用組織資源的法律或組織文件",
    optionC: "記載專案高層級目標、可交付成果與主要里程碑",
    optionD: "包含所有工作包的詳細任務甘特圖與每日排程",
    correctAnswers: "A,B,C",
    explanation: "專案章程是高階授權文件，不包含細部排程或每日甘特圖。",
    category: "專案管理",
    difficulty: "MEDIUM",
    tags: "起始階段, 專案章程",
  },
  {
    stem: "在風險評估矩陣中，風險值 (Risk Exposure / Risk Score) 通常是由哪兩個維度的乘積所決定？",
    type: "SINGLE",
    optionA: "發生機率 (Probability) 與 衝擊影響度 (Impact)",
    optionB: "專案成本與專案時程",
    optionC: "團隊規模與技術成熟度",
    optionD: "客戶滿意度與利潤率",
    correctAnswers: "A",
    explanation: "風險值 = 機率 (Probability) × 影響度 (Impact)，常用於定性與定量風險排序。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "風險管理",
  },
  {
    stem: "下列哪些情況屬於敏捷開發中「技術債 (Technical Debt)」的成因？",
    type: "MULTIPLE",
    optionA: "為求快速上線而忽略代碼重構與單元測試",
    optionB: "過時的第三方依賴套件長期未升級維護",
    optionC: "架構設計缺乏擴展性但未即時修正",
    optionD: "撰寫了過多高覆蓋率的自動化測試",
    correctAnswers: "A,B,C",
    explanation: "高覆蓋率測試有助於預防技術債，而非技術債的成因。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "軟體工程, 技術債",
  },

  // 資訊程式與 Web 架構
  {
    stem: "在 RESTful API 設計原則中，下列 HTTP 請求方法中哪些通常被視為具備等冪性 (Idempotent)？",
    type: "MULTIPLE",
    optionA: "GET",
    optionB: "PUT",
    optionC: "DELETE",
    optionD: "POST",
    correctAnswers: "A,B,C",
    explanation: "等冪性指多次調用與單次調用具相同結果。GET、PUT、DELETE 均為等冪；POST 會重複建立新資源，不具備等冪性。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "RESTful, HTTP",
  },
  {
    stem: "在關聯式資料庫 (RDBMS) 的 ACID 特性中，'C' 代表的是哪一個特性？",
    type: "SINGLE",
    optionA: "一致性 (Consistency)",
    optionB: "並行性 (Concurrency)",
    optionC: "相容性 (Compatibility)",
    optionD: "連線性 (Connectivity)",
    correctAnswers: "A",
    explanation: "ACID 代表 Atomicity (不可分割性/原子性)、Consistency (一致性)、Isolation (隔離性)、Durability (持久性)。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "資料庫, ACID",
  },
  {
    stem: "關於 Git 版本控制系統，下列哪些指令可以在不丟棄變更的情況下，將目前工作目錄的修改暫存以便切換分支？",
    type: "SINGLE",
    optionA: "git stash",
    optionB: "git clean -fd",
    optionC: "git reset --hard",
    optionD: "git branch -d",
    correctAnswers: "A",
    explanation: "git stash 可以將未提交的修改儲存到暫存堆疊中，待後續需要時再透過 git stash pop 復原。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "Git, 版本控制",
  },
  {
    stem: "在 Web 安全防護中，下列哪些措施有助於防範 SQL 注入攻擊 (SQL Injection)？",
    type: "MULTIPLE",
    optionA: "使用參數化查詢 (Parameterized Queries / Prepared Statements)",
    optionB: "使用 ORM (如 Prisma, Hibernate) 取代直接字串拼接 SQL",
    optionC: "對使用者輸入進行嚴格驗證與型別轉換",
    optionD: "在前端頁面上隱藏輸入框",
    correctAnswers: "A,B,C",
    explanation: "前端隱藏輸入框無法防止攻擊者直接透過網路封包發送惡意 SQL，必須由後端實施參數化與驗證。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "資安, SQL注入",
  },
  {
    stem: "在 HTTP/2 與 HTTP/1.1 的比較中，HTTP/2 引入了下列哪些重要改進？",
    type: "MULTIPLE",
    optionA: "二進位分幀層 (Binary Framing)",
    optionB: "多路複用 (Multiplexing)",
    optionC: "首部壓縮 (HPACK Header Compression)",
    optionD: "伺服器推送 (Server Push)",
    correctAnswers: "A,B,C,D",
    explanation: "四項均為 HTTP/2 相較於 HTTP/1.1 的核心重大演進架構。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "網路, HTTP/2",
  },
  {
    stem: "在 CSS Flexbox 佈局中，若要將子元素在主軸 (Main Axis) 方向完全居中對齊，應使用哪一個屬性值組合？",
    type: "SINGLE",
    optionA: "justify-content: center;",
    optionB: "align-items: center;",
    optionC: "align-content: center;",
    optionD: "flex-direction: center;",
    correctAnswers: "A",
    explanation: "justify-content 負責主軸對齊；align-items 負責交錯軸 (Cross Axis) 對齊。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "CSS, Flexbox",
  },
  {
    stem: "關於跨來源資源共用 (CORS, Cross-Origin Resource Sharing)，下列哪些情況會觸發瀏覽器的預檢請求 (Preflight Request, OPTIONS)？",
    type: "MULTIPLE",
    optionA: "HTTP 請求方法為 PUT 或 DELETE",
    optionB: "請求標頭包含自訂 Header (如 Authorization 或 X-Custom-Header)",
    optionC: "Content-Type 設為 application/json",
    optionD: "發送標準的 GET 請求且未攜帶自訂標頭",
    correctAnswers: "A,B,C",
    explanation: "標準簡單請求（GET/HEAD/POST 且 Content-Type 為 text/plain 等簡單型別）不會觸發預檢；非簡單請求均會觸發 OPTIONS 預檢。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "Web, CORS",
  },
  {
    stem: "在 Docker 容器化技術中，Dockerfile 裡的指令與作用，下列對應哪些是正確的？",
    type: "MULTIPLE",
    optionA: "FROM 用於指定基底映像檔 (Base Image)",
    optionB: "WORKDIR 用於設定容器內部的工作目錄",
    optionC: "COPY 用於將主機檔案複製到容器檔案系統內",
    optionD: "CMD 用於指定容器啟動時執行的預設命令",
    correctAnswers: "A,B,C,D",
    explanation: "四個選項皆為 Dockerfile 的核心標準指令與用途。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "Docker, DevOps",
  },
  {
    stem: "在關聯式資料庫中，建立索引 (Index) 能顯著加速查詢，但也可能帶來下列哪些代價？",
    type: "MULTIPLE",
    optionA: "增加資料庫檔案的磁碟儲存空間佔用",
    optionB: "降低 INSERT、UPDATE、DELETE 的寫入效能",
    optionC: "使資料庫查詢永遠無法使用 SELECT 指令",
    optionD: "在頻繁更新的資料表上增加索引維護開銷",
    correctAnswers: "A,B,D",
    explanation: "索引需要額外空間與每次寫入時重新維護 B-Tree，但不會限制任何 SQL 查詢語法。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "資料庫, 索引優化",
  },
  {
    stem: "下列何者是專門用來評估演算法時間複雜度的數學表示法？",
    type: "SINGLE",
    optionA: "大 O 符號 (Big O Notation)",
    optionB: "費馬小定理 (Fermat's Little Theorem)",
    optionC: "貝氏定理 (Bayes' Theorem)",
    optionD: "韋達定理 (Vieta's Formulas)",
    correctAnswers: "A",
    explanation: "大 O 符號 (Big O) 用於描述演算法在輸入資料規模無限增長時的時間或空間成長極限趨勢。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "資料結構, 演算法",
  },
  {
    stem: "在現代密碼學中，非對稱加密 (Asymmetric Encryption) 算法的特點包含下列哪些？",
    type: "MULTIPLE",
    optionA: "擁有一對金鑰：公鑰 (Public Key) 與 私鑰 (Private Key)",
    optionB: "公鑰可用於加密資料，私鑰用於解密資料",
    optionC: "私鑰可用於數位簽章，公鑰可用於驗證簽章",
    optionD: "加密與解密完全使用同一把金鑰",
    correctAnswers: "A,B,C",
    explanation: "使用同一把金鑰進行加解密的是「對稱加密」(Symmetric Encryption)，例如 AES。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "資訊安全, 密碼學",
  },
  {
    stem: "在瀏覽器儲存機制中，關於 localStorage 與 sessionStorage 的差異，下列敘述何者正確？",
    type: "SINGLE",
    optionA: "localStorage 資料在關閉分頁或瀏覽器後仍永久保存，sessionStorage 關閉分頁後即清除",
    optionB: "sessionStorage 的儲存空間比 localStorage 大 100 倍",
    optionC: "localStorage 只能在伺服器端存取，客戶端無法存取",
    optionD: "兩者每次 HTTP 請求時都會自動附帶在 Cookie 標頭傳送給伺服器",
    correctAnswers: "A",
    explanation: "localStorage 是永久性本地儲存，sessionStorage 生命週期僅限於當前瀏覽器分頁頁籤。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "前端, Web Storage",
  },
  {
    stem: "在 Linux 系統中，若要變更檔案的存取權限為「擁有者可讀寫執行、群組可讀執行、其他人僅可讀」，應使用哪一個 chmod 數字權限？",
    type: "SINGLE",
    optionA: "chmod 754 filename",
    optionB: "chmod 777 filename",
    optionC: "chmod 644 filename",
    optionD: "chmod 755 filename",
    correctAnswers: "A",
    explanation: "r=4, w=2, x=1。擁有者 4+2+1=7；群組 4+1=5；其他人 4。因此為 754。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "Linux, 權限",
  },
  {
    stem: "在微服務架構 (Microservices) 中，服務之間常見的非同步解耦通訊機制包含下列哪些？",
    type: "MULTIPLE",
    optionA: "訊息佇列 (Message Queue, 如 RabbitMQ, Apache Kafka)",
    optionB: "事件驅動架構 (Event-Driven Architecture)",
    optionC: "同步 HTTP REST 呼叫且未設置逾時",
    optionD: "發布/訂閱模式 (Pub/Sub Pattern)",
    correctAnswers: "A,B,D",
    explanation: "同步 HTTP 呼叫是強耦合的同步通訊，容易引發連鎖雪崩；訊息佇列與 Pub/Sub 才是非同步解耦機制。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "系統架構, 微服務",
  },
  {
    stem: "在 React 18+ 與 Next.js App Router 架構中，關於伺服器端元件 (Server Components, RSC) 的特點，下列敘述哪些是正確的？",
    type: "MULTIPLE",
    optionA: "RSC 在伺服器端渲染，產物不包含 JavaScript 打包體積 (Zero Bundle Size)",
    optionB: "RSC 可以直接存取伺服器端資料庫與內部檔案系統",
    optionC: "RSC 不能直接使用 useState 或 useEffect 等客戶端 Hook",
    optionD: "RSC 無法直接監聽 onClick 或 onChange 等瀏覽器使用者互動事件",
    correctAnswers: "A,B,C,D",
    explanation: "RSC 運行於伺服器環境，沒有客戶端生命週期與瀏覽器 DOM 事件，需透過 'use client' 標記轉換為客戶端元件。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "React, Next.js",
  },
  {
    stem: "在專案組態中，環境變數 (Environment Variables) 應遵循的最佳實踐原則包含下列哪些？",
    type: "MULTIPLE",
    optionA: "資料庫密碼與 API 私密金鑰切勿提交 (Commit) 到公開的 Git 倉庫",
    optionB: "使用 .env.example 提供範本說明各變數名稱與功用",
    optionC: "生產環境 (Production) 與開發環境 (Development) 應使用彼此隔離的金鑰與連線字串",
    optionD: "將所有私密金鑰直接寫死在客戶端前端程式碼中以利呼叫",
    correctAnswers: "A,B,C",
    explanation: "將金鑰硬編碼在客戶端代碼中會直接暴露給任何訪問網站的使用者，造成極大資安漏洞。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "DevOps, 資安",
  },
  {
    stem: "在資料結構中，堆疊 (Stack) 與 佇列 (Queue) 分別遵循哪種資料存取順序原則？",
    type: "SINGLE",
    optionA: "Stack 遵循 LIFO (後進先出)，Queue 遵循 FIFO (先進先出)",
    optionB: "Stack 遵循 FIFO (先進先出)，Queue 遵循 LIFO (後進先出)",
    optionC: "兩者皆遵循隨機存取原則",
    optionD: "兩者皆遵循優先權排序原則",
    correctAnswers: "A",
    explanation: "Stack 為 Last-In-First-Out (後進先出)；Queue 為 First-In-First-Out (先進先出)。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "資料結構",
  },
  {
    stem: "在關聯式資料庫中，SQL 的哪一種 JOIN 類型會回傳左側資料表的所有紀錄，即使右側資料表沒有符合條件的對應資料？",
    type: "SINGLE",
    optionA: "LEFT OUTER JOIN (左外部連接)",
    optionB: "INNER JOIN (內部連接)",
    optionC: "RIGHT OUTER JOIN (右外部連接)",
    optionD: "CROSS JOIN (交叉連接)",
    correctAnswers: "A",
    explanation: "LEFT JOIN 會保證保留左表的全部資料列，右表無匹配時補 NULL。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "SQL, JOIN",
  },
  {
    stem: "在持續整合與持續交付 (CI/CD) 流程中，自動化流水線 (Pipeline) 通常會包含下列哪些關鍵階段？",
    type: "MULTIPLE",
    optionA: "靜態程式碼分析與語法檢查 (Linting)",
    optionB: "自動化單元測試與整合測試 (Unit & Integration Testing)",
    optionC: "建置打包與容器映像檔封裝 (Building & Packaging)",
    optionD: "自動化部署至測試或生產環境 (Deployment)",
    correctAnswers: "A,B,C,D",
    explanation: "現代 CI/CD 標準管線涵蓋 Lint、Test、Build 與 Deploy 完整四個階段。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "DevOps, CI/CD",
  },
  {
    stem: "下列哪些技術可以用來防止 Web 應用程式遭受跨站請求偽造 (CSRF, Cross-Site Request Forgery) 攻擊？",
    type: "MULTIPLE",
    optionA: "在敏感表單請求中加入隨機產生的 CSRF Token",
    optionB: "Cookie 屬性設定 SameSite=Strict 或 SameSite=Lax",
    optionC: "伺服器校驗 Origin 與 Referer 請求標頭",
    optionD: "完全關閉所有伺服器日誌紀錄",
    correctAnswers: "A,B,C",
    explanation: "關閉日誌無法防禦 CSRF，反而使攻擊難以追查。CSRF Token、SameSite Cookie 與 Header 檢驗是標準防護措施。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "資安, CSRF",
  },
  {
    stem: "在軟體設計模式 (Design Patterns) 中，觀察者模式 (Observer Pattern) 的主要核心理念為何？",
    type: "SINGLE",
    optionA: "定義物件間一對多的依賴關係，當一個物件狀態改變時，所有依賴它的物件都會自動收到通知並更新",
    optionB: "保證一個類別只有一個實例，並提供全域存取點",
    optionC: "將抽象部分與它的實現部分分離，使它們都可以獨立變化",
    optionD: "動態地給一個物件添加一些額外的職責",
    correctAnswers: "A",
    explanation: "A 選項為觀察者模式 (Observer / PubSub) 的經典定義；B 為單例模式 (Singleton)；C 為橋接模式 (Bridge)；D 為裝飾者模式 (Decorator)。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "設計模式",
  },
  {
    stem: "在網頁效能優化指標中，Google Core Web Vitals (核心網頁體驗指標) 包含下列哪三個核心維度？",
    type: "MULTIPLE",
    optionA: "LCP (Largest Contentful Paint - 最大內容繪製)",
    optionB: "INP (Interaction to Next Paint - 與下次繪製的互動延遲)",
    optionC: "CLS (Cumulative Layout Shift - 累計版面配置位移)",
    optionD: "DNS (Domain Name System 查詢次數)",
    correctAnswers: "A,B,C",
    explanation: "Core Web Vitals 官方指標目前由載入效能 LCP、互動回應能力 INP 與視覺穩定度 CLS 三者構成。",
    category: "資訊程式",
    difficulty: "HARD",
    tags: "前端, 效能指標",
  },
  {
    stem: "在物件導向程式設計 (OOP) 的四大基本支柱中，不包含下列何者？",
    type: "SINGLE",
    optionA: "封裝 (Encapsulation)",
    optionB: "繼承 (Inheritance)",
    optionC: "多型 (Polymorphism)",
    optionD: "遞迴 (Recursion)",
    correctAnswers: "D",
    explanation: "OOP 四大特性為封裝、繼承、多型與抽象 (Abstraction)。遞迴是一種演算法概念，不屬於 OOP 支柱。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "OOP, 程式設計",
  },
  {
    stem: "關於非同步 JavaScript (Async JavaScript)，下列敘述哪些是正確的？",
    type: "MULTIPLE",
    optionA: "Promise 有三種狀態：Pending (進行中)、Fulfilled (已實現)、Rejected (已拒絕)",
    optionB: "async 函式內部可以使用 await 關鍵字等待 Promise 解析",
    optionC: "事件循環 (Event Loop) 的微任務 (Microtask) 優先序高於巨集任務 (Macrotask)",
    optionD: "JavaScript 是多執行緒語言，每執行一個函式就會在底層建立一個獨立的作業系統執行緒",
    correctAnswers: "A,B,C",
    explanation: "JavaScript 引擎主執行緒是單執行緒 (Single-threaded) 搭配事件循環架構，而非為每個函式建立 OS 執行緒。",
    category: "資訊程式",
    difficulty: "MEDIUM",
    tags: "JavaScript, 異步機制",
  },
  {
    stem: "在現代雲端架構中，何謂「無伺服器計算 (Serverless Computing / FaaS)」？",
    type: "SINGLE",
    optionA: "開發者只需撰寫商業邏輯函式，伺服器資源、自動縮放與高可用性完全由雲端平台託管",
    optionB: "網站完全不需要任何伺服器即可在斷網環境下全球運行",
    optionC: "使用者必須自建實體機房並自行維護 Linux 核心更新",
    optionD: "一種不需要任何資料庫就能永久保存資料的技術",
    correctAnswers: "A",
    explanation: "Serverless (如 AWS Lambda, Cloudflare Workers) 並非沒有伺服器，而是底層架構抽象化由雲端服務商全權自動調度。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "雲端運算, Serverless",
  },
  {
    stem: "在專案交付階段，「使用者驗收測試 (UAT, User Acceptance Testing)」的主要目的為何？",
    type: "SINGLE",
    optionA: "由業務使用者或客戶驗證系統是否符合真實業務需求與操作流程",
    optionB: "由開發人員測試底層演算法的時間複雜度",
    optionC: "由資料庫管理員測試磁碟陣列的讀寫速率",
    optionD: "測試編譯器是否支援最新語法特性",
    correctAnswers: "A",
    explanation: "UAT 是系統上線前最後一道關鍵驗收關卡，由業務端或終端使用者確認系統能否解決實際業務問題。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "品質管理, UAT",
  },
  {
    stem: "下列哪些技術常被用於前端頁面或靜態資源的全球就近快取加速？",
    type: "SINGLE",
    optionA: "CDN (內容傳遞網路, Content Delivery Network)",
    optionB: "RAID 0 磁碟陣列",
    optionC: "VPN 虛擬私人網路",
    optionD: "UPS 不斷電系統",
    correctAnswers: "A",
    explanation: "CDN 透過分佈在全球的邊緣節點 (Edge Nodes) 快取靜態資源，讓終端使用者能就近取得內容以大幅降低延遲。",
    category: "資訊程式",
    difficulty: "EASY",
    tags: "網路, CDN",
  },
  {
    stem: "在敏捷回顧會議 (Sprint Retrospective) 中，常見的討論框架包含下列哪些經典維度？",
    type: "MULTIPLE",
    optionA: "哪些事情進行得很順利 (What went well)",
    optionB: "哪些地方可以做得更好 (What could be improved)",
    optionC: "下一衝刺我們將採取什麼具體行動 (Action items)",
    optionD: "公開指責並處罰產能最低的工程師",
    correctAnswers: "A,B,C",
    explanation: "回顧會議堅持不咎責原則 (Blameless Retrospective)，專注於流程改善與團隊協作，而非個人處罰。",
    category: "專案管理",
    difficulty: "EASY",
    tags: "敏捷, 回顧會議",
  },
];

async function main() {
  console.log(`總共有 ${questionsPool.length} 道題庫範本，開始植入...`);
  let createdCount = 0;
  let skippedCount = 0;

  for (const q of questionsPool) {
    const norm = normalizeText(q.stem);
    const existing = await prisma.question.findFirst({
      where: { normalizedStem: norm },
    });
    if (!existing) {
      await prisma.question.create({
        data: {
          ...q,
          normalizedStem: norm,
        },
      });
      createdCount++;
    } else {
      skippedCount++;
    }
  }

  const total = await prisma.question.count();
  console.log(`植入完成！本次新增: ${createdCount} 題，已存在略過: ${skippedCount} 題，目前題庫總數: ${total} 題！`);
}

main()
  .catch((e) => {
    console.error("植入失敗:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
